### ISSUE TITLE
Newly added paygates don’t appear in checkout page

### ISSUE THREAD

**Issue by hamed-azimi** [fahrirusliyadi/fr-multi-bank-transfer-payment-gateways-for-woocommerce#1]
As explained in https://wordpress.org/support/topic/newly-added-paygates-dont-appear-in-checkout-page/

I also tested it on the default theme, and still, it didn't appear on the checkout page.

Hopefully, you can release a hotfix for it, or let me know if there is any snippet I can add to make it work.

Thanks

**Comment by fahrirusliyadi** [comment]
Have you also tested with all plugins disabled except WooCommerce and this plugin?
